### ISSUE TITLE
Incomplete installation instructions

### ISSUE THREAD

**Issue by ithgub** [zesaver/conky_godville#1]
`godville.py` relies on module `requests`, which is absent on my machine and whose installation is not mentioned in https://github.com/zesaver/conky_godville#installing
I have been unsuccessful with `pip` on my machine (anitX 19 i.e. Debian 10 Buster without systemd), so I can't use conky_godville

Please, provide a working way of installing `requests` or if possible facilitate relying on alternative downloaders: curl/wget/aria2/...

**Comment by zesaver** [comment]
@ithgub Hello and thank you for submitting the issue. Just pushed the commit replacing the requests module with urllib, which should require no separate installation. Can you check it, please?

**Comment by ithgub** [comment]
Yes, works for me. Від бога до бога дякую :)
